before_script:
  - psql -c 'create database wtforms_alchemy_test;' -U postgres


language: python
python:
  - 2.6
  - 2.7
  - 3.3

env:
  matrix:
    - WTFORMS=WTForms==1.0.5
    - WTFORMS=wtforms2

install:
  - "if [ $WTFORMS = wtforms2 ]; then export WTFORMS=https://github.com/wtforms/wtforms/archive/master.zip; fi"
  - "pip install $WTFORMS"
  - pip install -e ".[test]"

script:
  - python setup.py test
